'use strict';
const test=require('node:test');
const {prefix,eq,start,run}=require('./helpers');
for(const optimize of ['-O0','-O2']){
 test(`musical: escrita, distribuição, ajuda e limites ${optimize}`,()=>run(`
ChamarxMusicaPosicaoFa[4,2]
${eq('@ULTIMO',0,'InSd32')}
ChamarxMusicaPosicaoFa[3,3]
${eq('@ULTIMO',6,'InSd32')}
ChamarxJogoEscreverNota[@Notas,0,8,0]
ChamarxJogoEscreverNota[@Notas,1,13,0]
ChamarxMusicaAltura[Notas@0.letra,Notas@0.oitava,Notas@0.alteracao]
DefVarInSd32xPitchy@ULTIMO
ChamarxMusicaAltura[Notas@1.letra,Notas@1.oitava,Notas@1.alteracao]
${eq('@ULTIMO','@Pitch','InSd32')}
${eq('Notas@0.letra',0,'InSd32')}${eq('Notas@1.letra',1,'InSd32')}
${start}
// Cada natural aparece duas ou três vezes em vinte exercícios.
ParaxC[0,8,1]
DefVarInSd64xContagemy0
InSd64ParaInSd32[@C]
DefVarInSd32xCodigoy@ULTIMO
ParaIndiceSOAxI[@Notas]
CompararIgualxyInSd32xNotas@@I.codigoy@Codigo
Sex@ULTIMO
SomarxyInSd64x@Contagemy1
SetVarInSd64xContagemy@ULTIMO
FimSe
FimPara
CompararMaiorIgualxyInSd64x@Contagemy2
Exigir[@ULTIMO]
CompararMenorIgualxyInSd64x@Contagemy3
Exigir[@ULTIMO]
FimPara
ChamarxJogoAjuda[@Estado,@Notas,1000]
ChamarxJogoAjuda[@Estado,@Notas,1000]
ChamarxJogoResponder[@Estado,@Notas,Notas@0.letra,0,Falso,1000]
${eq('@Estado.pontos',0)}${eq('@Estado.ajudas',1)}${eq('@Estado.cursor',1)}
ChamarxJogoResponder[@Estado,@Notas,Notas@1.letra,0,Verdadeiro,2000]
${eq('@Estado.cursor',1)}
ChamarxJogoResponder[@Estado,@Notas,Notas@1.letra,0,Falso,3000]
${eq('@Estado.pontos',0)}${eq('@Estado.erros',1)}
SetVarInSd32xConfig.modoy2
${start}
SubtrxyInSd64xNotas@0.alvoy9600
ChamarxJogoResponder[@Estado,@Notas,Notas@0.letra,0,Falso,@ULTIMO]
${eq('@Estado.pontos',10)}
SubtrxyInSd64xNotas@1.alvoy9601
ChamarxJogoResponder[@Estado,@Notas,Notas@1.letra,0,Falso,@ULTIMO]
${eq('@Estado.pontos',10)}${eq('@Estado.erros',1)}
SomarxyInSd64xNotas@2.alvoy9600
ChamarxJogoResponder[@Estado,@Notas,Notas@2.letra,0,Falso,@ULTIMO]
${eq('@Estado.pontos',20)}
SomarxyInSd64xNotas@3.alvoy9601
ChamarxJogoExpirar[@Estado,@Notas,@ULTIMO]
${eq('@Estado.erros',2)}
ChamarxJogoPosicaoX[@Estado,@Notas,4,Notas@4.alvo]
${eq('@ULTIMO','230.0','Fl64')}
`,optimize));
 test(`musical: campanha, cem rodadas, perfil transacional ${optimize}`,()=>run(`
ParaxRodada[1,101,1]
ChamarxJogoIniciar[@Estado,@Notas,@Historico,@Config,@Relogio,1000000000,42,@Rodada]
ParaIndiceSOAxI[@Notas]
SomarxyInSd64xNotas@@I.alvoy0
ChamarxJogoResponder[@Estado,@Notas,Notas@@I.letra,Notas@@I.alteracao,Falso,@ULTIMO]
FimPara
Exigir[@Estado.concluida]
${eq('@Estado.pontos',200)}
ChamarxJogoConsolidar[@Perfil,@Dominios,@Estatisticas,@Resultados,@Estado,@Notas]
// Repetir a consolidação nunca concede pontos duas vezes.
ChamarxJogoConsolidar[@Perfil,@Dominios,@Estatisticas,@Resultados,@Estado,@Notas]
CompararIgualxyInSd64x@Rodaday2
Sex@ULTIMO
SetVarInSd32xConfig.modoy1
FimSe
CompararIgualxyInSd64x@Rodaday4
Sex@ULTIMO
SetVarInSd32xConfig.modoy0
SetVarInSd32xConfig.clavey1
FimSe
CompararIgualxyInSd64x@Rodaday6
Sex@ULTIMO
SetVarInSd32xConfig.modoy1
FimSe
CompararIgualxyInSd64x@Rodaday8
Sex@ULTIMO
SetVarInSd32xConfig.modoy2
SetVarInSd32xConfig.clavey0
FimSe
CompararIgualxyInSd64x@Rodaday10
Sex@ULTIMO
SetVarInSd64xConfig.bpmy90
FimSe
CompararIgualxyInSd64x@Rodaday14
Sex@ULTIMO
SetVarInSd64xConfig.bpmy120
FimSe
CompararIgualxyInSd64x@Rodaday16
Sex@ULTIMO
SetVarInSd32xConfig.clavey1
SetVarInSd64xConfig.bpmy60
FimSe
CompararIgualxyInSd64x@Rodaday18
Sex@ULTIMO
SetVarInSd64xConfig.bpmy90
FimSe
CompararIgualxyInSd64x@Rodaday20
Sex@ULTIMO
SetVarInSd64xConfig.bpmy120
SetVarBlxConfig.acidentesyVerdadeiro
FimSe
ChamarxJogoLiberado[@Perfil,@Dominios,@Config]
Exigir[@ULTIMO]
FimPara
${eq('@Perfil.pontos',20000)}${eq('@Perfil.quantidade',50)}${eq('Resultados@49.id',51)}
ChamarxJogoMusicaLiberada[@Perfil,@Dominios,1]
Exigir[@ULTIMO]
ChamarxJogoMusicaLiberada[@Perfil,@Dominios,2]
Exigir[@ULTIMO]
SetVarRegistro<JogoConfiguracao>xPerfil.configy@Config
DefRecursoxDocumentoyJsonCriar[4194304]
ChamarxJogoPerfilGravar[@Perfil,@Dominios,@Estatisticas,@Resultados,@Vinculos,@Documento]
DefStkFB1048576CxArquivoyl''
JsonEscrever[@Documento,@Arquivo]
DefRecursoxLidoyJsonLer[@Arquivo,4194304]
SetVarInSd64xPerfil.pontosy0
ChamarxJogoPerfilLer[@Lido,@Perfil,@Dominios,@Estatisticas,@Resultados,@Vinculos]
${eq('@Perfil.pontos',20000)}
JsonDefinirInSd64[@Lido,l'/versao',2]
DefVarBlxCapturouyFalso
Tentar
ChamarxJogoPerfilLer[@Lido,@Perfil,@Dominios,@Estatisticas,@Resultados,@Vinculos]
CapturarxErro
SetVarBlxCapturouyVerdadeiro
FimTentar
Exigir[@Capturou]
${eq('@Perfil.pontos',20000)}
JsonDefinirInSd64[@Lido,l'/versao',1]
JsonDefinirInSd64[@Lido,l'/Resultados/49/acertos',21]
SetVarBlxCapturouyFalso
Tentar
ChamarxJogoPerfilLer[@Lido,@Perfil,@Dominios,@Estatisticas,@Resultados,@Vinculos]
CapturarxErro
SetVarBlxCapturouyVerdadeiro
FimTentar
Exigir[@Capturou]
${eq('@Perfil.pontos',20000)}${eq('Resultados@49.acertos',20)}
`,optimize));
}
