'use strict';
const {eq}=require('./helpers');
const fixture=`Importar[l'tom/replay']
DefRegistroxJogoReplayResultado
PropInSd64xpontos
PropInSd64xacertos
PropInSd64xcomandos
PropInSd64xchecksum
FimDef
DefFuncaoxTesteRelogio[InSd64xDecorrido]yRegistro<RelogioAudio>
DefVarRegistro<RelogioAudio>xClockyPadrao
DefVarInSd64xMusicaly@Decorrido
CompararMaiorIgualxyInSd64x@Decorridoy11000000000
Sex@ULTIMO
CompararMenorxyInSd64x@Decorridoy13000000000
Sex@ULTIMO
SetVarInSd64xMusicaly11000000000
SetVarBlxClock.pausadoyVerdadeiro
Senao
SubtrxyInSd64x@Decorridoy2000000000
SetVarInSd64xMusicaly@ULTIMO
FimSe
FimSe
MultiplicarDividirInSd64[@Musical,48000,1000000000]
SetVarInSd64xClock.posicaoy@ULTIMO
SetVarInSd64xClock.ancoraAmostray@ULTIMO
SomarxyInSd64x@Decorridoy1000000000
SetVarInSd64xClock.ancoraNsy@ULTIMO
Retornarx@Clock
FimFuncao

DefFuncaoxTesteReproduzir[InSd64xFps,BlxAtrasar]yRegistro<JogoReplayResultado>
DefVarRegistro<JogoEstado>xModeloyPadrao
DefVarRegistro<JogoPerfil>xPerfilLocalyPadrao
DefVarRegistro<RelogioAudio>xClockyPadrao
SetVarBlxClock.pausadoyVerdadeiro
SetVarInSd64xClock.ancoraNsy1000000000
DefArraySoAxExerciciosxJogoNotax20
DefArraySoAxTrechosxSessaoTrechox64
DefArraySoAxAssociacoesxEntradaVinculox9
DefArraySoAxActionsxEntradaAcaox9
DefVarRegistro<ReplayEstado>xGravacaoyPadrao
DefArraySoAxEventListxReplayEventox128
DefVarRegistro<EntradaEvento>xInputyPadrao
ChamarxJogoPerfilPadrao[@PerfilLocal,@Associacoes]
ChamarxJogoPadrao[]
DefVarRegistro<JogoConfiguracao>xConfigLocaly@ULTIMO
SetVarInSd32xConfigLocal.modoy2
ChamarxJogoIniciar[@Modelo,@Exercicios,@Trechos,@ConfigLocal,@Clock,1000000000,42,1]
ChamarxReplayIniciar[@Gravacao,1000000000,@Clock,42,54]
ChamarxTesteRelogio[0]
SetVarRegistro<RelogioAudio>xClocky@ULTIMO
SetVarInSd64xInput.tempoNsy1000000000
ChamarxReplayAdicionar[@Gravacao,@EventList,@Input,@Clock,@Input.tempoNs]
ParaIndiceSOAxI[@Exercicios]
CompararIgualxyInSd64x@Iy4
Sex@ULTIMO
SetVarInSd32xInput.tipoy@EVENTO_PERDER_FOCO
SetVarInSd64xInput.tempoNsy12000000000
ChamarxTesteRelogio[11000000000]
SetVarRegistro<RelogioAudio>xClocky@ULTIMO
ChamarxReplayAdicionar[@Gravacao,@EventList,@Input,@Clock,@Input.tempoNs]
SetVarInSd32xInput.tipoy@EVENTO_GANHAR_FOCO
SetVarInSd64xInput.tempoNsy14000000000
ChamarxTesteRelogio[13000000000]
SetVarRegistro<RelogioAudio>xClocky@ULTIMO
ChamarxReplayAdicionar[@Gravacao,@EventList,@Input,@Clock,@Input.tempoNs]
FimSe
MultiplicarDividirInSd64[Exercicios@@I.alvo,1000000000,48000]
DefVarInSd64xElapsedy@ULTIMO
CompararMaiorIgualxyInSd64x@Iy4
Sex@ULTIMO
SomarxyInSd64x@Elapsedy2000000000
SetVarInSd64xElapsedy@ULTIMO
FimSe
ChamarxTesteRelogio[@Elapsed]
SetVarRegistro<RelogioAudio>xClocky@ULTIMO
SomarxyInSd64x@Elapsedy1000000000
SetVarInSd64xInput.tempoNsy@ULTIMO
SetVarInSd32xInput.tipoy@EVENTO_PRESSIONAR
DefVarInSd32xLetrayExercicios@@I.letra
SetVarInSd32xInput.teclayAssociacoes@@Letra.codigo
SomarxyInSd32x@Letray4
SetVarInSd32xInput.fisicay@ULTIMO
SetVarInSd32xInput.repeticaoy0
ChamarxReplayAdicionar[@Gravacao,@EventList,@Input,@Clock,@Input.tempoNs]
// Mesmo horário: a repetição deve conservar a ordem e não julgar outra nota.
SetVarInSd32xInput.repeticaoy1
ChamarxReplayAdicionar[@Gravacao,@EventList,@Input,@Clock,@Input.tempoNs]
SetVarInSd32xInput.tipoy@EVENTO_SOLTAR
SetVarInSd32xInput.repeticaoy0
ChamarxReplayAdicionar[@Gravacao,@EventList,@Input,@Clock,@Input.tempoNs]
FimPara
DefVarRegistro<JogoReplayResultado>xResultyPadrao
DefVarInSd64xQuadroy0
DefVarBlxRodandoyVerdadeiro
Enquantox@Rodando
MultiplicarDividirInSd64[@Quadro,1000000000,@Fps]
DefVarInSd64xElapsedFramey@ULTIMO
DefVarBlxPular yFalso
Sex@Atrasar
CompararMaiorIgualxyInSd64x@ElapsedFramey3990000000
DefVarBlxDepoisy@ULTIMO
CompararMenorxyInSd64x@ElapsedFramey4890000000
ExyBlx@ULTIMOy@Depois
SetVarBlxPulary@ULTIMO
FimSe
NaoBlx@Pular
Sex@ULTIMO
DefVarBlxTemyVerdadeiro
Enquantox@Tem
ChamarxReplayProximo[@Gravacao,@EventList,@ElapsedFrame,@Input,@Clock]
SetVarBlxTemy@ULTIMO
Sex@Tem
ChamarxJogoEntrada[@Modelo,@Exercicios,@Trechos,@Associacoes,@Actions,@Input,@Clock,@Gravacao.momentoNs]
Sex@Modelo.emitir
SomarxyInSd64x@Result.comandosy1
SetVarInSd64xResult.comandosy@ULTIMO
FimSe
FimSe
FimEnquanto
ChamarxTesteRelogio[@ElapsedFrame]
SetVarRegistro<RelogioAudio>xClocky@ULTIMO
SomarxyInSd64x@ElapsedFramey1000000000
ChamarxSessaoAtualizar[@Modelo.sessao,@Trechos,@Clock,@ULTIMO]
NaoBlx@Clock.pausado
Sex@ULTIMO
ChamarxJogoExpirar[@Modelo,@Exercicios,@Clock.posicao]
FimSe
ChamarxJogoPosicaoX[@Modelo,@Exercicios,0,192000]
${eq('@ULTIMO','230.0','Fl64')}
FimSe
SomarxyInSd64x@Quadroy1
SetVarInSd64xQuadroy@ULTIMO
NaoBlx@Modelo.concluida
SetVarBlxRodandoy@ULTIMO
CompararMaiorxyInSd64x@ElapsedFramey46000000000
Sex@ULTIMO
Falhar[6]
FimSe
FimEnquanto
SetVarInSd64xResult.pontosy@Modelo.pontos
SetVarInSd64xResult.acertosy@Modelo.acertos
ParaIndiceSOAxI[@Exercicios]
SomarxyInSd64x@Result.checksumyExercicios@@I.resposta
SetVarInSd64xResult.checksumy@ULTIMO
Exigir[Exercicios@@I.pontuou]
FimPara
Retornarx@Result
FimFuncao
ChamarxTesteReproduzir[30,Falso]
DefVarRegistro<JogoReplayResultado>xR30y@ULTIMO
ChamarxTesteReproduzir[60,Verdadeiro]
DefVarRegistro<JogoReplayResultado>xR60y@ULTIMO
ChamarxTesteReproduzir[144,Verdadeiro]
DefVarRegistro<JogoReplayResultado>xR144y@ULTIMO
${eq('@R30.pontos',200)}${eq('@R30.comandos',20)}${eq('@R30.acertos',20)}
${['pontos','acertos','comandos','checksum'].map(f=>eq('@R30.'+f,'@R60.'+f)+eq('@R30.'+f,'@R144.'+f)).join('')}
`.replace('DefVarBlxPular y','DefVarBlxPulary');

module.exports=fixture;
